### ISSUE TITLE
preserve lines and edges

### ISSUE THREAD

**Issue by SangenBR** [Patman86/SVT-AV1-Mod-by-Patman#1]
hello, do you have any settings that help preserve lines and edges in anime? because the much loss compared to x264 or x265 due to the strong denoise that av1 applies

**Comment by Patman86** [comment]
hi, I can't recommend any settings for you quickly, but take a look here:
[Reddit](https://www.reddit.com/r/AV1/comments/wcpny5/encoding_my_anime_library_with_av1_with_focus_on/)
or ask in the Doom9 forum or on Discord (StaxRip).
