### ISSUE TITLE
not enough

### ISSUE THREAD

**Issue by Andrasolin** [Patman86/SVT-AV1-Mod-by-Patman#10]
wanted to lower the 1.9gb MB without losing quality...

checked SVT-AV1 in Hybrid and your mod in StaxRip
In Hybrid - the native one is used - processed with deterioration of the image and FPS
In StaxRip v.2440 your mod has been processed Beautifully! but there is not enough Bit Switching. Please add.

![001](https://github.com/user-attachments/assets/ce0365dc-f89a-4e84-bf81-f570b72ce302)

**Comment by Patman86** [comment]
Thanks for reporting this issue, which is related to StaxRip. @Dendraspis needs the info.

**Comment by Dendraspis** [comment]
@Andrasolin  
Great, you have found somebody who can ping/spam me for you.   😁 

But nothing is needed as `SvtAv1EncApp` does not change the bit depth regardless your settings. You have to use `AviSynth`/`VapourSynth` to change the bit depth before passing it to the encoder.
