### ISSUE TITLE
dovi and hdr10plus paths in `app_config.h` code change

### ISSUE THREAD

**Issue by ItachiUchiha-IU** [Patman86/SVT-AV1-Mod-by-Patman#11]
Hi, I wanted to simply tell u that I used your code change to build dovi and hdr10plus and it works perfectly, but in the lines [here](https://github.com/Patman86/SVT-AV1-Mod-by-Patman/blob/4b543e8e7f271ab1a77bb66b155c6792a8b336b3/Source/App/app_config.h#L17-L38) the paths to the libraries didnt work for me, and I had to remove `../` from the 4 paths. I am using w10, so could it simply be a w10 vs w11 thing? idk. Or maybe it's just me not understanding what folders I had to put the libraries in: the files were put into `svt-av1-psy\Source\API\dovi\msvc\include\libdovi\rpu_parser.h` etc.

Thank you for your work!

**Comment by Patman86** [comment]
Hi, my source folders for the Dovi/HDR10Plus libraries are located directly in the source folder, so I have included this part in the directory structure. It has nothing to do with Windows. The path must always be adapted to the corresponding conditions.

**Comment by ItachiUchiha-IU** [comment]
I see, yes in fact it works keeping the files outside of the API folder.
Okay now I know the meaning of `../` 👌, thx!
