### ISSUE TITLE
PGO build binaries?

### ISSUE THREAD

**Issue by gitoss** [Patman86/SVT-AV1-Mod-by-Patman#8]
Are the (Windows) releases build with PGO enabled? https://github.com/Patman86/SVT-AV1-Mod-by-Patman/releases/tag/v2.2.0

It not, make this a request :-) ... according to the commit, pgo should be significantly faster to make it worth the trouble. https://gitlab.com/AOMediaCodec/SVT-AV1/-/merge_requests/2254

PGO doesn't seem to be possible for VC as far as I can tell - though I've managed to compile SVT-AV1 w/ VS and CLANG (even manually added the latest clang release to VS).

**Comment by Patman86** [comment]
The releases created with VS are not with PGO enabled. I have tried it and it does not have the same effect with VS as with Clang or LLVM. LTO enabled is much more efficient here. Perhaps something will change in the future with vs.
